apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  labels:
    run: hello-world-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    run: hello-world-pod
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  selector:
    matchLabels:
      run: hello-world-pod
  replicas: 1
  template:
    metadata:
      labels:
        run: hello-world-pod
    spec:
      containers:
      - name: hello-world-container
        image:"gcr.io/quiet-container-260904/hello-world"
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80

